# Generated by Django 3.2.8 on 2021-10-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Викторины'},
        ),
    ]
